All: program

program:
	javac -d . BoardTypes.java
	javac -d . CellState.java
	javac -d . HW8.java
	javac -d . Jbuttons.java
	javac -d . PegClass.java
	javac -d . PegSolitaireGame.java
	javac -d . RadioButtons.java
	java hw8.HW8
